<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Asistente plugin          |
 |                                                                       |
 | Copyright (C) Tu Nombre o el del Equipo                              |
 |                                                                       |
 | Licenciado bajo GNU GPL v3 o superior                                |
 +-----------------------------------------------------------------------+
*/

$labels['asistente'] = 'Asistente';
$labels['asistente.title'] = 'Asistente de redacción por voz';

